// Generated by `dart run flutter_control_center:setup`.
// This file is yours: change titles, SF Symbols, payloads and add controls.
// The setup command does not overwrite it unless you pass --force.

import SwiftUI
import WidgetKit

/// Toggle "focus_mode"; drive it from Dart with
/// `FlutterControlCenter.setToggleState('focus_mode', true)`.
struct FocusModeControl: FlutterControlToggle {
  static let kind = "focus_mode"
  let title = "Focus mode"
  let systemImageOn = "moon.fill"
  let systemImageOff = "moon"
}

/// Button "start_timer"; opens the app and delivers a
/// `ControlAction` with this kind to Dart.
struct StartTimerControl: FlutterControlButton {
  static let kind = "start_timer"
  let title = "Start timer"
  let systemImage = "timer"
  var payload: [String: String] { ["minutes": "25"] }
}

@main
struct ControlCenterExtensionBundle: WidgetBundle {
  var body: some Widget {
    FocusModeControl()
    StartTimerControl()
  }
}
