// Generated by `dart run flutter_control_center:setup`.
// Re-running the setup command rewrites this file.

/// Values shared with the Flutter app. They must match
/// `FlutterControlCenter.configure(appGroup:)` and the app's CFBundleURLTypes.
enum FlutterControlCenterConfiguration {
  /// App Group enabled for both the Runner target and this extension.
  static let appGroup = "group.com.manishpanday.flutterControlCenterExample"
  /// URL scheme registered by the Runner target; buttons open the app with it.
  static let urlScheme = "fccexample"
}
