import 'dart:io';

/// Header written at the top of every file generated by the setup command.
const String generatedHeader =
    '// Generated by `dart run flutter_control_center:setup`.';

/// File name of the shared storage protocol (copied from the plugin sources).
const String storeFileName = 'FlutterControlCenterStore.swift';

/// File name of the Widget Extension kit (copied from the plugin sources).
const String kitFileName = 'FlutterControls.swift';

/// File name of the generated App Group / URL scheme configuration.
const String configurationFileName = 'FlutterControlCenterConfiguration.swift';

/// Maximum number of controls one `WidgetBundle` body can list directly.
const int maxControlsPerBundle = 10;

final RegExp _kindPattern = RegExp(r'^[A-Za-z][A-Za-z0-9_.-]*$');
final RegExp _schemePattern = RegExp(r'^[A-Za-z][A-Za-z0-9+.-]*$');
final RegExp _identifierPattern = RegExp(r'^[A-Za-z][A-Za-z0-9_]*$');
final RegExp _appGroupPattern = RegExp(
  r'^group\.[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*$',
);

/// Thrown when setup options are invalid; [message] is shown to the user.
class SetupException implements Exception {
  /// Creates the exception.
  const SetupException(this.message);

  /// What is wrong and how to fix it.
  final String message;

  @override
  String toString() => message;
}

/// Kind of Swift control generated for a [ControlSpec].
enum ControlSpecType {
  /// A `FlutterControlToggle`.
  toggle,

  /// A `FlutterControlButton`.
  button,
}

/// One control to generate in the extension's `WidgetBundle`.
class ControlSpec {
  /// Creates a spec; prefer [ControlSpec.parse].
  const ControlSpec({
    required this.kind,
    required this.title,
    required this.type,
  });

  /// Parses `kind` or `kind:Title` as given to `--toggle` / `--button`.
  factory ControlSpec.parse(String raw, ControlSpecType type) {
    final int colon = raw.indexOf(':');
    final String kind = (colon < 0 ? raw : raw.substring(0, colon)).trim();
    final String title = colon < 0 ? '' : raw.substring(colon + 1).trim();
    if (!_kindPattern.hasMatch(kind)) {
      throw SetupException(
        'Invalid control kind "$kind": use letters, digits, "_", "." or "-", '
        'starting with a letter (e.g. focus_mode).',
      );
    }
    return ControlSpec(
      kind: kind,
      title: title.isEmpty ? _titleFromKind(kind) : title,
      type: type,
    );
  }

  /// The control kind shared between Swift and Dart.
  final String kind;

  /// Title shown on the control.
  final String title;

  /// Whether a toggle or a button is generated.
  final ControlSpecType type;

  /// Swift struct name, e.g. `focus_mode` -> `FocusModeControl`.
  String get structName {
    final String base = kind
        .split(RegExp(r'[_.-]+'))
        .where((String part) => part.isNotEmpty)
        .map((String part) => part[0].toUpperCase() + part.substring(1))
        .join();
    return '${base}Control';
  }

  static String _titleFromKind(String kind) {
    final String words = kind.split(RegExp(r'[_.-]+')).join(' ').trim();
    return words[0].toUpperCase() + words.substring(1);
  }
}

/// Everything the setup command needs.
class SetupOptions {
  /// Creates options; call [validate] before use.
  const SetupOptions({
    required this.iosDirectory,
    required this.extensionName,
    this.appGroup,
    this.urlScheme,
    this.controls = const <ControlSpec>[],
    this.force = false,
    this.updateKitOnly = false,
  });

  /// The Flutter app's `ios/` directory.
  final String iosDirectory;

  /// Name of the Widget Extension target (and its folder under `ios/`).
  final String extensionName;

  /// App Group shared by the app and the extension, e.g. `group.com.x.app`.
  final String? appGroup;

  /// URL scheme registered by the app (CFBundleURLTypes), e.g. `myapp`.
  final String? urlScheme;

  /// Controls to generate in the bundle.
  final List<ControlSpec> controls;

  /// Overwrite user-editable files that already exist.
  final bool force;

  /// Only refresh the two library files (after upgrading the plugin).
  final bool updateKitOnly;

  /// Directory the extension files are written to.
  String get extensionDirectory =>
      '$iosDirectory${Platform.pathSeparator}$extensionName';

  /// Throws [SetupException] when an option is invalid.
  void validate() {
    if (!Directory(iosDirectory).existsSync()) {
      throw SetupException(
        'iOS directory "$iosDirectory" does not exist. Run this from your '
        'Flutter app root or pass --ios-dir.',
      );
    }
    if (!_identifierPattern.hasMatch(extensionName)) {
      throw SetupException(
        'Invalid extension name "$extensionName": use letters, digits and "_", '
        'starting with a letter.',
      );
    }
    if (updateKitOnly) {
      return;
    }
    final String? group = appGroup;
    if (group == null || !_appGroupPattern.hasMatch(group)) {
      throw SetupException(
        'Pass --app-group with an App Group identifier such as '
        '"group.com.example.app" (got ${group ?? 'nothing'}).',
      );
    }
    final String? scheme = urlScheme;
    if (scheme == null || !_schemePattern.hasMatch(scheme)) {
      throw SetupException(
        'Pass --url-scheme with a URL scheme such as "myapp": letters, digits, '
        '"+", "." or "-", starting with a letter (got ${scheme ?? 'nothing'}).',
      );
    }
    if (controls.isEmpty) {
      throw const SetupException(
        'Declare at least one control with --toggle kind:Title or '
        '--button kind:Title.',
      );
    }
    if (controls.length > maxControlsPerBundle) {
      throw const SetupException(
        'A WidgetBundle body lists at most $maxControlsPerBundle controls; '
        'generate fewer and group the rest by hand.',
      );
    }
    final Set<String> kinds = <String>{};
    final Set<String> structs = <String>{};
    for (final ControlSpec control in controls) {
      if (!kinds.add(control.kind)) {
        throw SetupException('Control kind "${control.kind}" is used twice.');
      }
      if (!structs.add(control.structName)) {
        throw SetupException(
          'Kinds map to the same Swift type ${control.structName}; rename one.',
        );
      }
    }
  }
}

/// What the setup command did.
class SetupResult {
  /// Creates a result.
  const SetupResult({
    required this.written,
    required this.skipped,
    required this.conflictingFiles,
  });

  /// Files created or replaced.
  final List<String> written;

  /// User-editable files left untouched because they exist (use --force).
  final List<String> skipped;

  /// Other Swift files in the extension folder that declare `@main` or a
  /// widget/control (typically Xcode's target template) and must be deleted.
  final List<String> conflictingFiles;
}

/// Locates the Swift sources shipped with the plugin.
class KitSources {
  /// Creates the locator for the plugin checkout at [packageRoot].
  const KitSources(this.packageRoot);

  /// Root directory of the flutter_control_center package.
  final String packageRoot;

  /// Path of the shared store source.
  String get storePath => _join(<String>[
    packageRoot,
    'ios',
    'flutter_control_center',
    'Sources',
    'flutter_control_center',
    storeFileName,
  ]);

  /// Path of the extension kit source.
  String get kitPath => _join(<String>[
    packageRoot,
    'ios',
    'FlutterControlCenterKit',
    kitFileName,
  ]);
}

String _join(List<String> parts) => parts.join(Platform.pathSeparator);

/// Writes the extension files described by [options] using the plugin sources
/// in [sources]. Throws [SetupException] for invalid options.
SetupResult runSetup(SetupOptions options, KitSources sources) {
  options.validate();
  final Directory extensionDir = Directory(options.extensionDirectory);
  extensionDir.createSync(recursive: true);

  final List<String> written = <String>[];
  final List<String> skipped = <String>[];

  void write(String name, String contents, {required bool userEditable}) {
    final File file = File(_join(<String>[extensionDir.path, name]));
    if (userEditable && file.existsSync() && !options.force) {
      skipped.add(file.path);
      return;
    }
    file.writeAsStringSync(contents);
    written.add(file.path);
  }

  for (final String source in <String>[sources.storePath, sources.kitPath]) {
    final File file = File(source);
    if (!file.existsSync()) {
      throw SetupException(
        'Plugin source $source is missing; reinstall flutter_control_center.',
      );
    }
    write(
      file.uri.pathSegments.last,
      file.readAsStringSync(),
      userEditable: false,
    );
  }

  if (!options.updateKitOnly) {
    write(
      configurationFileName,
      configurationSource(options.appGroup!, options.urlScheme!),
      userEditable: false,
    );
    write(
      bundleFileName(options.extensionName),
      bundleSource(options.extensionName, options.controls),
      userEditable: true,
    );
  }

  return SetupResult(
    written: written,
    skipped: skipped,
    conflictingFiles: findConflictingFiles(extensionDir, options.extensionName),
  );
}

/// File name of the generated `WidgetBundle`.
String bundleFileName(String extensionName) => '${extensionName}Bundle.swift';

/// Swift source of `FlutterControlCenterConfiguration`.
String configurationSource(String appGroup, String urlScheme) =>
    '''
$generatedHeader
// Re-running the setup command rewrites this file.

/// Values shared with the Flutter app. They must match
/// `FlutterControlCenter.configure(appGroup:)` and the app's CFBundleURLTypes.
enum FlutterControlCenterConfiguration {
  /// App Group enabled for both the Runner target and this extension.
  static let appGroup = "${_swiftString(appGroup)}"
  /// URL scheme registered by the Runner target; buttons open the app with it.
  static let urlScheme = "${_swiftString(urlScheme)}"
}
''';

/// Swift source of the extension's `WidgetBundle` listing [controls].
String bundleSource(String extensionName, List<ControlSpec> controls) {
  final StringBuffer out = StringBuffer()
    ..writeln(generatedHeader)
    ..writeln(
      '// This file is yours: change titles, SF Symbols, payloads and add '
      'controls.',
    )
    ..writeln(
      '// The setup command does not overwrite it unless you pass --force.',
    )
    ..writeln()
    ..writeln('import SwiftUI')
    ..writeln('import WidgetKit')
    ..writeln();
  for (final ControlSpec control in controls) {
    final String kind = _swiftString(control.kind);
    final String title = _swiftString(control.title);
    switch (control.type) {
      case ControlSpecType.toggle:
        out
          ..writeln('/// Toggle "$kind"; drive it from Dart with')
          ..writeln("/// `FlutterControlCenter.setToggleState('$kind', true)`.")
          ..writeln('struct ${control.structName}: FlutterControlToggle {')
          ..writeln('  static let kind = "$kind"')
          ..writeln('  let title = "$title"')
          ..writeln('  let systemImageOn = "checkmark.circle.fill"')
          ..writeln('  let systemImageOff = "circle"')
          ..writeln('}');
      case ControlSpecType.button:
        out
          ..writeln('/// Button "$kind"; opens the app and delivers a')
          ..writeln('/// `ControlAction` with this kind to Dart.')
          ..writeln('struct ${control.structName}: FlutterControlButton {')
          ..writeln('  static let kind = "$kind"')
          ..writeln('  let title = "$title"')
          ..writeln('  let systemImage = "app.badge"')
          ..writeln('  var payload: [String: String] { [:] }')
          ..writeln('}');
    }
    out.writeln();
  }
  out
    ..writeln('@main')
    ..writeln('struct ${extensionName}Bundle: WidgetBundle {')
    ..writeln('  var body: some Widget {');
  for (final ControlSpec control in controls) {
    out.writeln('    ${control.structName}()');
  }
  out
    ..writeln('  }')
    ..writeln('}');
  return out.toString();
}

/// Swift files in [extensionDir], other than the generated ones, that declare
/// `@main` or a widget/control — they would clash with the generated bundle.
List<String> findConflictingFiles(
  Directory extensionDir,
  String extensionName,
) {
  final Set<String> ours = <String>{
    storeFileName,
    kitFileName,
    configurationFileName,
    bundleFileName(extensionName),
  };
  final RegExp declaration = RegExp(
    r'@main|:\s*(Widget|ControlWidget|WidgetBundle)\b',
  );
  final List<String> conflicts = <String>[];
  if (!extensionDir.existsSync()) {
    return conflicts;
  }
  for (final FileSystemEntity entity in extensionDir.listSync()) {
    if (entity is! File || !entity.path.endsWith('.swift')) {
      continue;
    }
    if (ours.contains(entity.uri.pathSegments.last)) {
      continue;
    }
    if (declaration.hasMatch(entity.readAsStringSync())) {
      conflicts.add(entity.path);
    }
  }
  conflicts.sort();
  return conflicts;
}

/// The manual Xcode steps, with the concrete names from [options].
String xcodeSteps(SetupOptions options) {
  final String ext = options.extensionName;
  final String group = options.appGroup ?? '<your App Group>';
  final String scheme = options.urlScheme ?? '<your URL scheme>';
  return '''
Xcode steps (once per app; they edit signing and project.pbxproj, so they are not automated):

 1. open ios/Runner.xcworkspace
 2. File > New > Target... > iOS > Widget Extension > Next.
    Product Name: $ext. Untick "Include Live Activity", "Include Control" and
    "Include Configuration App Intent". Embed in Application: Runner. Finish,
    and choose "Don't Activate" when asked about the scheme.
 3. Delete Xcode's template Swift files in ios/$ext (move to trash) except
    ${bundleFileName(ext)}, then re-run this command with --force so the
    generated ${bundleFileName(ext)} replaces Xcode's.
 4. Select the $ext target > General > Minimum Deployments: iOS 18.0.
 5. Runner target > Signing & Capabilities > + Capability > App Groups > add "$group".
    Do the same for the $ext target (same group). Both targets need the same Team.
 6. Runner target > Info > URL Types > + : Identifier "$scheme", URL Schemes "$scheme".
 7. Runner target > Build Phases: drag "Embed Foundation Extensions" above
    "Thin Binary" (otherwise Flutter builds fail with "Cycle inside Runner").
 8. Optional: $ext target > Build Settings > set MARKETING_VERSION to
    \$(FLUTTER_BUILD_NAME) and CURRENT_PROJECT_VERSION to \$(FLUTTER_BUILD_NUMBER)
    so the extension version always matches the app.
 9. In Dart, before using controls:
      await FlutterControlCenter.configure(appGroup: '$group');
10. flutter run on an iOS 18+ device or simulator, then add the controls from
    Control Center > + > Add a Control.
''';
}

String _swiftString(String value) =>
    value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
